apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-rybn
  namespace: appstudio-e2e-test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: jvm-build-suite-application-runs
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: jvm-build-suite-component-rybn
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: jvm-build-suite-component-rybn-
      labels:
        build.appstudio.openshift.io/application: jvm-build-suite-application-runs
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: jvm-build-suite-component-rybn
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: appstudio-e2e-test
    spec:
      params:
      - name: git-url
        value: https://github.com/stuartwdouglas/hacbs-test-project
      - name: output-image
        value: quay.io/redhat-appstudio-qe/test-images:6acee096a69147429e6dae9826bffc1b-$(tt.params.git-revision)
      - name: revision
        value: main
      pipelineRef:
        bundle: quay.io/gabemontero/hacbs-templates-bundle:2022-08-23-110459
        name: java-builder
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: jvm-build-suite-component-rybn/$(tt.params.git-revision)
    status: {}
status: {}
