apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-rybn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-rybn
    app.kubernetes.io/part-of: jvm-build-suite-application-runs
  name: jvm-build-suite-component-rybn
  namespace: appstudio-e2e-test
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jvm-build-suite-component-rybn
    weight: 100
status: {}
